name: 'Common - Build and Publish'

on: [push]

jobs:
  box:
    name: 'Box'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build the Docker image'
        run: docker build --tag ajardin/humbug-box:latest common/humbug-box/

      - name: 'Sign in to Docker Hub'
        run: docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'

      - name: 'Publish the Docker image'
        run: docker push ajardin/humbug-box:latest
        if: github.ref == 'refs/heads/master'

  phpcpd:
    name: 'PHP Copy/Paste Detector'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build the Docker image'
        run: docker build --tag ajardin/phpcpd:latest common/phpcpd/

      - name: 'Sign in to Docker Hub'
        run: docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'

      - name: 'Publish the Docker image'
        run: docker push ajardin/phpcpd:latest
        if: github.ref == 'refs/heads/master'

  phpcsfixer:
    name: 'PHP-CS-Fixer'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build the Docker image'
        run: docker build --tag ajardin/phpcsfixer:latest common/phpcsfixer/

      - name: 'Sign in to Docker Hub'
        run: docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'

      - name: 'Publish the Docker image'
        run: docker push ajardin/phpcsfixer:latest
        if: github.ref == 'refs/heads/master'

  phpstan:
    name: 'PHPStan'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build the Docker image'
        run: docker build --tag ajardin/phpstan:latest common/phpstan/

      - name: 'Sign in to Docker Hub'
        run: docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'

      - name: 'Publish the Docker image'
        run: docker push ajardin/phpstan:latest
        if: github.ref == 'refs/heads/master'

  security-checker:
    name: 'Security Checker'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build the Docker image'
        run: docker build --tag ajardin/security-checker:latest common/security-checker/

      - name: 'Sign in to Docker Hub'
        run: docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'

      - name: 'Publish the Docker image'
        run: docker push ajardin/security-checker:latest
        if: github.ref == 'refs/heads/master'
