name: 'Copy/Paste Detector image'

on:
  push:
    branches: ['**']
    paths:
      - '.github/workflows/common-phpcpd.yml'
      - 'common/phpcpd/**'
  schedule:
    - cron: "0 0 * * *"

jobs:

  phpcpd:
    name: 'Main'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build & Publish the Docker image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/phpcpd
          path: common/phpcpd/
          always_pull: true
          tags: latest
          push: ${{ github.ref == 'refs/heads/master' }}
