name: "Security Checker image"

on:
  push:
    branches: ["**"]
    paths:
      - ".github/workflows/common-security-checker.yml"
      - "common/security-checker/**"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:

jobs:

  security-checker:
    name: "Main"
    runs-on: ubuntu-latest

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v1

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./common/security-checker/
          file: ./common/security-checker/Dockerfile
          tags: ajardin/security-checker:latest
          push: ${{ github.ref == 'refs/heads/master' }}
