name: 'Elasticsearch for Magento 2 image'

on:
  push:
    branches: ['**']
    paths:
      - '.github/workflows/magento2-elasticsearch.yml'
      - 'magento2/elasticsearch/**'
  schedule:
    - cron: "0 0 * * *"

jobs:

  elasticsearch:
    name: 'Main'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build & Publish the Docker image (Elasticsearch 6.8)'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/magento2-elasticsearch
          path: magento2/elasticsearch/6.8
          always_pull: true
          tags: 6.8, latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: 'Build & Publish the Docker image (Elasticsearch 7.6)'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/magento2-elasticsearch
          path: magento2/elasticsearch/7.6
          always_pull: true
          tags: 7.6
          push: ${{ github.ref == 'refs/heads/master' }}
