name: "PHP 8.0 images"

on:
  push:
    branches: ["**"]
    paths:
      - ".github/workflows/php-80.yml"
      - "php/8.0/**"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image (default)"
        uses: docker/build-push-action@v2
        with:
          context: ./php/8.0/
          file: ./php/8.0/Dockerfile
          tags: ajardin/php:8.0
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: "Build & Publish the Docker image (Blackfire)"
        uses: docker/build-push-action@v2
        with:
          context: ./php/8.0/blackfire/
          file: ./php/8.0/blackfire/Dockerfile
          tags: ajardin/php:8.0-blackfire
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: "Build & Publish the Docker image (Xdebug)"
        uses: docker/build-push-action@v2
        with:
          context: ./php/8.0/xdebug/
          file: ./php/8.0/xdebug/Dockerfile
          tags: ajardin/php:8.0-xdebug
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
