name: 'Sylius images'

on:
  push:
    branches: ['**']
    paths:
      - '.github/workflows/sylius.yml'
      - '.github/workflows/symfony.yml'
      - 'common/blackfire-entrypoint/**'
      - 'common/nginx/**'
      - 'symfony/**'
      - 'sylius/**'

jobs:
  php:
    name: 'PHP'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build & Publish the Docker image (7.3)'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/sylius-php
          path: sylius/php/7.3
          always_pull: true
          tags: 7.3
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: 'Build & Publish the Docker image (7.4)'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/sylius-php
          path: sylius/php/7.4
          always_pull: true
          tags: 7.4, latest
          push: ${{ github.ref == 'refs/heads/master' }}
